### ISSUE TITLE
Agent stops working after a while

### ISSUE THREAD

**Issue by YigitDemirag** [openai/universe-starter-agent#46]
I am using 16CPU EC2 and running 8 workers on it. Eventually, my rewards go to zero and when I connect with vnc to check, I see no action is taken by worker. After a while, I get following info. I don't have any idea what may cause it. My error looks like that

```
universe-RaMjBj-0 | [2017-01-08 18:30:19,623] [INFO:universe.pyprofile] [pyprofile] period=5.02s timers={"rewarder.sleep": {"std": "142.90us", "mean": "16.24ms", "calls": 301}, "rewarder.frame": {"std": "
23.78us", "mean": "16.79ms", "calls": 301}, "reward.parsing.score": {"std": "12.80us", "mean": "281.21us", "calls": 23}, "score.crop_cache.get.MatchImage": {"std": "2.96us", "mean": "47.54us", "calls": 23
}, "rewarder.compute_reward": {"std": "124.65us", "mean": "243.00us", "calls": 301}, "reward.parsing.gameover": {"std": "5.12us", "mean": "103.48us", "calls": 23}, "vnc_env.VNCEnv.vnc_session.step": {"std
": "17.97us", "mean": "72.58us", "calls": 301}, "score.crop_cache.get.OCRScorerV0": {"std": "3.24us", "mean": "84.88us", "calls": 23}} counters={"agent_conn.reward": {"std": 0, "mean": 0.0, "calls": 1}, "
reward.vnc.updates.n": {"std": 0.26609850880794444, "mean": 0.07641196013289042, "calls": 301}, "score.crop_cache.hit.MatchImage": {"std": 0.0, "mean": 1.0, "calls": 23}, "score.crop_cache.hit.OCRScorerV0
": {"std": 0.0, "mean": 1.0, "calls": 23}} gauges={"reward_parser.score.last_score": {"std": 0.0, "mean": 41.0, "calls": 23, "value": 41.0}} (export_time=108.96us)
universe-RaMjBj-0 | [2017-01-08 18:30:19,623] [INFO:universe.rewarder.remote] [Rewarder] Over past 5.02s, sent 1 reward messages to agent: reward=0 reward_min=0 reward_max=0 done=False info={'rewarder.vnc
.updates.bytes': 0, 'rewarder.vnc.updates.n': 0, 'rewarder.vnc.updates.pixels': 0, 'rewarder.profile': '<1573 bytes>'}
universe-RaMjBj-0 | [2017-01-08 18:30:24,639] [INFO:universe.wrappers.logger] Stats for the past 5.02s: vnc_updates_ps=4.6 n=1 reaction_time=None observation_lag=None action_lag=None reward_ps=0.0 reward_
total=0.0 vnc_bytes_ps[total]=5930.2 vnc_pixels_ps[total]=43993.2 reward_lag=None rewarder_message_lag=None fps=60.01
universe-RaMjBj-0 | [2017-01-08 18:30:24,640] [INFO:universe.pyprofile] [pyprofile] period=5.02s timers={"rewarder.sleep": {"std": "155.25us", "mean": "16.23ms", "calls": 301}, "rewarder.frame": {"std": "
24.60us", "mean": "16.79ms", "calls": 301}, "reward.parsing.score": {"std": "12.91us", "mean": "280.01us", "calls": 23}, "score.crop_cache.get.MatchImage": {"std": "1.40us", "mean": "47.06us", "calls": 23
}, "rewarder.compute_reward": {"std": "126.64us", "mean": "243.67us", "calls": 301}, "reward.parsing.gameover": {"std": "3.80us", "mean": "101.80us", "calls": 23}, "vnc_env.VNCEnv.vnc_session.step": {"std
": "47.10us", "mean": "74.96us", "calls": 301}, "score.crop_cache.get.OCRScorerV0": {"std": "4.33us", "mean": "85.29us", "calls": 23}} counters={"agent_conn.reward": {"std": 0, "mean": 0.0, "calls": 1}, "
reward.vnc.updates.n": {"std": 0.2660985088079445, "mean": 0.07641196013289045, "calls": 301}, "score.crop_cache.hit.MatchImage": {"std": 0.0, "mean": 1.0, "calls": 23}, "score.crop_cache.hit.OCRScorerV0"
: {"std": 0.0, "mean": 1.0, "calls": 23}} gauges={"reward_parser.score.last_score": {"std": 0.0, "mean": 41.0, "calls": 23, "value": 41.0}} (export_time=107.53us)
universe-RaMjBj-0 | [2017-01-08 18:30:24,640] [INFO:universe.rewarder.remote] [Rewarder] Over past 5.02s, sent 1 reward messages to agent: reward=0 reward_min=0 reward_max=0 done=False info={'rewarder.vnc
.updates.bytes': 0, 'rewarder.vnc.updates.n': 0, 'rewarder.vnc.updates.pixels': 0, 'rewarder.profile': '<1572 bytes>'}
universe-RaMjBj-0 | [2017-01-08 18:30:29,656] [INFO:universe.wrappers.logger] Stats for the past 5.02s: vnc_updates_ps=4.6 n=1 reaction_time=None observation_lag=None action_lag=None reward_ps=0.0 reward_
total=0.0 vnc_bytes_ps[total]=6052.5 vnc_pixels_ps[total]=44785.4 reward_lag=None rewarder_message_lag=None fps=60.01
universe-RaMjBj-0 | [2017-01-08 18:30:29,656] [INFO:universe.pyprofile] [pyprofile] period=5.02s timers={"rewarder.sleep": {"std": "143.80us", "mean": "16.23ms", "calls": 301}, "rewarder.frame": {"std": "
22.46us", "mean": "16.79ms", "calls": 301}, "reward.parsing.score": {"std": "15.82us", "mean": "283.26us", "calls": 23}, "score.crop_cache.get.MatchImage": {"std": "6.98us", "mean": "49.24us", "calls": 23
}, "rewarder.compute_reward": {"std": "121.48us", "mean": "243.62us", "calls": 301}, "reward.parsing.gameover": {"std": "8.45us", "mean": "106.37us", "calls": 23}, "vnc_env.VNCEnv.vnc_session.step": {"std
": "17.72us", "mean": "73.30us", "calls": 301}, "score.crop_cache.get.OCRScorerV0": {"std": "3.60us", "mean": "85.27us", "calls": 23}} counters={"agent_conn.reward": {"std": 0, "mean": 0.0, "calls": 1}, "
reward.vnc.updates.n": {"std": 0.2660985088079444, "mean": 0.07641196013289046, "calls": 301}, "score.crop_cache.hit.MatchImage": {"std": 0.0, "mean": 1.0, "calls": 23}, "score.crop_cache.hit.OCRScorerV0"
: {"std": 0.0, "mean": 1.0, "calls": 23}} gauges={"reward_parser.score.last_score": {"std": 0.0, "mean": 41.0, "calls": 23, "value": 41.0}} (export_time=102.52us)
universe-RaMjBj-0 | [2017-01-08 18:30:29,657] [INFO:universe.rewarder.remote] [Rewarder] Over past 5.02s, sent 1 reward messages to agent: reward=0 reward_min=0 reward_max=0 done=False info={'rewarder.vnc
.updates.bytes': 0, 'rewarder.vnc.updates.n': 0, 'rewarder.vnc.updates.pixels': 0, 'rewarder.profile': '<1578 bytes>'}
```
After for a while watching this non-action on all my workers, I got this error: 
```
universe-U6zfHu-0 | [2017-01-08 18:35:52,590] [INFO:universe.rewarder.remote] [Rewarder] Over past 5.02s, sent 1 reward messages to agent: reward=0 reward_min=0 reward_max=0 done=False info={'rewarder.vnc.updates.bytes': 0, 'rewarder.vnc.updates.n': 0, 'rewarder.profile': '<1577 bytes>', 'rewarder.vnc.updates.pixels': 0}
universe-U6zfHu-0 | [nginx] 2017/01/08 18:35:56 [info] 62#62: *47 client closed connection while waiting for request, client: 172.17.0.1, server: 0.0.0.0:15900
universe-U6zfHu-0 | [nginx] 2017/01/08 18:35:56 [info] 62#62: *48 client closed connection while waiting for request, client: 172.17.0.1, server: 0.0.0.0:15900
universe-U6zfHu-0 | [nginx] 2017/01/08 18:35:56 [info] 62#62: *49 client closed connection while waiting for request, client: 172.17.0.1, server: 0.0.0.0:15900
universe-U6zfHu-0 | [nginx] 2017/01/08 18:35:56 [info] 62#62: *50 client closed connection while waiting for request, client: 172.17.0.1, server: 0.0.0.0:15900
universe-U6zfHu-0 | [nginx] 2017/01/08 18:35:56 [info] 62#62: *51 client closed connection while waiting for request, client: 172.17.0.1, server: 0.0.0.0:15900
universe-U6zfHu-0 | [nginx] 2017/01/08 18:35:56 [info] 62#62: *52 client closed connection while waiting for request, client: 172.17.0.1, server: 0.0.0.0:15900
universe-U6zfHu-0 | [nginx] 2017/01/08 18:35:56 [info] 62#62: *53 client closed connection while waiting for request, client: 172.17.0.1, server: 0.0.0.0:15900
universe-U6zfHu-0 | [nginx] 2017/01/08 18:35:56 [info] 62#62: *54 client closed connection while waiting for request, client: 172.17.0.1, server: 0.0.0.0:15900
universe-U6zfHu-0 | [nginx] 2017/01/08 18:35:56 [info] 62#62: *55 client closed connection while waiting for request, client: 172.17.0.1, server: 0.0.0.0:15900
universe-U6zfHu-0 | [nginx] 2017/01/08 18:35:56 [info] 62#62: *56 client closed connection while waiting for request, client: 172.17.0.1, server: 0.0.0.0:15900
universe-U6zfHu-0 | [2017-01-08 18:35:57,606] [INFO:universe.wrappers.logger] Stats for the past 5.02s: vnc_updates_ps=4.6 n=1 reaction_time=None observation_lag=None action_lag=None reward_ps=0.0 reward_total=0.0 vnc_bytes_ps[total]=5908.2 vnc_pixels_ps[total]=43801.3 reward_lag=None rewarder_message_lag=None fps=60.01
universe-U6zfHu-0 | [2017-01-08 18:35:57,606] [INFO:universe.pyprofile] [pyprofile] period=5.02s timers={"score.crop_cache.get.OCRScorerV0": {"mean": "85.79us", "calls": 23, "std": "7.72us"}, "score.crop_cache.get.MatchImage": {"mean": "49.62us", "calls": 23, "std": "2.81us"}, "rewarder.compute_reward": {"mean": "249.79us", "calls": 301, "std": "121.38us"}, "rewarder.sleep": {"mean": "16.23ms", "calls": 301, "std": "139.39us"}, "vnc_env.VNCEnv.vnc_session.step": {"mean": "75.64us", "calls": 301, "std": "18.30us"}, "rewarder.frame": {"mean": "16.79ms", "calls": 301, "std": "30.29us"}, "rewarder_protocol.latency.rtt.skew_unadjusted": {"mean": "1.21ms", "calls": 10, "std": "491.26us"}, "reward.parsing.score": {"mean": "278.84us", "calls": 23, "std": "12.59us"}, "reward.parsing.gameover": {"mean": "107.23us", "calls": 23, "std": "6.68us"}} counters={"agent_conn.reward": {"std": 0, "calls": 1, "mean": 0.0}, "reward.vnc.updates.n": {"std": 0.26609850880794456, "calls": 301, "mean": 0.0764119601328904}, "rewarder_protocol.messages": {"std": 0.0, "calls": 10, "mean": 1.0}, "rewarder_protocol.messages.v0.control.ping": {"std": 0.0, "calls": 10, "mean": 1.0}, "score.crop_cache.hit.MatchImage": {"std": 0.0, "calls": 23, "mean": 1.0}, "score.crop_cache.hit.OCRScorerV0": {"std": 0.0, "calls": 23, "mean": 1.0}} gauges={"reward_parser.score.last_score": {"mean": 41.0, "std": 0.0, "calls": 23, "value": 41.0}} (export_time=116.83us)
universe-U6zfHu-0 | [2017-01-08 18:35:57,606] [INFO:universe.rewarder.remote] [Rewarder] Over past 5.02s, sent 1 reward messages to agent: reward=0 reward_min=0 reward_max=0 done=False info={'rewarder.vnc.updates.bytes': 0, 'rewarder.vnc.updates.n': 0, 'rewarder.profile': '<1904 bytes>', 'rewarder.vnc.updates.pixels': 0}
Traceback (most recent call last):
  File "worker.py", line 123, in <module>
    tf.app.run()
  File "/home/ubuntu/anaconda3/envs/agents/lib/python3.5/site-packages/tensorflow/python/platform/app.py", line 30, in run
    sys.exit(main(sys.argv[:1] + flags_passthrough))
  File "worker.py", line 115, in main
    run(args, server)
  File "worker.py", line 62, in run
    trainer.process(sess)
  File "/home/ubuntu/Downloads/universe-starter-agent/a3c.py", line 257, in process
    rollout = self.pull_batch_from_queue()
  File "/home/ubuntu/Downloads/universe-starter-agent/a3c.py", line 241, in pull_batch_from_queue
    rollout = self.runner.queue.get(timeout=600.0)
  File "/home/ubuntu/anaconda3/envs/agents/lib/python3.5/queue.py", line 172, in get
    raise Empty
queue.Empty
[2017-01-08 18:35:59,661] Killing and removing container: id=8d5388841769fd6245a92c3b017ee048654af9a0c79867354276b7706a3c8e73
```

**Comment by tlbtlbtlb** [comment]
We're not sure what causes this. We're trying to track it down. Restarting the worker will generally work (it'll reload its state from the checkpoint and continue making progress.)

**Comment by yaroslavvb** [comment]
Are there any messages in worker/ps tmux windows ? Your issue could be caused by worker thread crashing as in https://github.com/openai/universe-starter-agent/issues/44

This would mean model is not initialized, no rollouts are added to the queue, so rollout consumer thread will die with empty after 600 seconds.
