### ISSUE TITLE
AttributeError: 'VectorizeFilter' object has no attribute 'filter_n'

### ISSUE THREAD

**Issue by jhurliman** [openai/universe-starter-agent#49]
Following the setup instructions on OSX I get most of the way toward a working setup, but training fails with this message:

```
[2017-01-11 14:46:17,526] Starting training at step=0
Exception in thread Thread-1:
Traceback (most recent call last):
  File "/Users/jhurliman/anaconda/envs/universe-starter-agent/lib/python3.5/threading.py", line 914, in _bootstrap_inner
    self.run()
  File "/Users/jhurliman/Code/openai/universe-starter-agent/a3c.py", line 92, in run
    self._run()
  File "/Users/jhurliman/Code/openai/universe-starter-agent/a3c.py", line 101, in _run
    self.queue.put(next(rollout_provider), timeout=600.0)
  File "/Users/jhurliman/Code/openai/universe-starter-agent/a3c.py", line 112, in env_runner
    last_state = env.reset()
  File "/Users/jhurliman/anaconda/envs/universe-starter-agent/lib/python3.5/site-packages/gym/core.py", line 123, in reset
    observation = self._reset()
  File "/Users/jhurliman/anaconda/envs/universe-starter-agent/lib/python3.5/site-packages/universe/wrappers/vectorize.py", line 46, in _reset
    observation_n = self.env.reset()
  File "/Users/jhurliman/anaconda/envs/universe-starter-agent/lib/python3.5/site-packages/gym/core.py", line 123, in reset
    observation = self._reset()
  File "/Users/jhurliman/anaconda/envs/universe-starter-agent/lib/python3.5/site-packages/universe/vectorized/vectorize_filter.py", line 27, in _reset
    observation_n = [filter._after_reset(observation) for filter, observation in zip(self.filter_n, observation_n)]
AttributeError: 'VectorizeFilter' object has no attribute 'filter_n'
```

**Comment by jhurliman** [comment]
I see this is a problem in `universe` that was recently fixed upstream, I need to either switch to the master branch of universe or wait for a new version to publish to pip.

https://github.com/openai/universe/issues/96

**Comment by tlbtlbtlb** [comment]
You can work around it for now by calling `env.configure()` right after `env=gym.make(...)`

**Comment by tlbtlbtlb** [comment]
PyPI now has universe 0.21.2, which fixes the problem
