### ISSUE TITLE
getting started problem

### ISSUE THREAD

**Issue by iHateInventNames** [openai/universe-starter-agent#64]
$ pip install conda
Collecting conda
  Downloading conda-4.2.7.tar.gz (235kB)
    100% |████████████████████████████████| 235kB 1.7MB/s 
Building wheels for collected packages: conda
  Running setup.py bdist_wheel for conda ... done
  Stored in directory: /Users/sergejkrivonos/Library/Caches/pip/wheels/aa/94/d8/a845fe13112e0e3bdc3f907702a06c0b3ba66d90903060e467
Successfully built conda
Installing collected packages: conda
Successfully installed conda-4.2.7
MacBook-Sergej:~ sergejkrivonos$ conda create --name universe-starter-agent python=3.5
Traceback (most recent call last):
  File "/usr/local/bin/conda", line 7, in <module>
    from conda.cli.main import main
  File "/usr/local/lib/python2.7/site-packages/conda/cli/__init__.py", line 8, in <module>
    from .main import main  # NOQA
  File "/usr/local/lib/python2.7/site-packages/conda/cli/main.py", line 46, in <module>
    from ..base.context import context
  File "/usr/local/lib/python2.7/site-packages/conda/base/context.py", line 13, in <module>
    from .constants import DEFAULT_CHANNELS, DEFAULT_CHANNEL_ALIAS, ROOT_ENV_NAME, SEARCH_PATH, conda
  File "/usr/local/lib/python2.7/site-packages/conda/base/constants.py", line 13, in <module>
    from enum import Enum
ImportError: No module named enum
MacBook-Sergej:~ sergejkrivonos$ pip install enum numpy
Collecting enum
  Downloading enum-0.4.6.tar.gz
Collecting numpy
  Downloading numpy-1.12.0-cp27-cp27m-macosx_10_6_intel.macosx_10_9_intel.macosx_10_9_x86_64.macosx_10_10_intel.macosx_10_10_x86_64.whl (4.4MB)
    100% |████████████████████████████████| 4.4MB 215kB/s 
Requirement already satisfied: setuptools in /usr/local/lib/python2.7/site-packages (from enum)
Building wheels for collected packages: enum
  Running setup.py bdist_wheel for enum ... done
  Stored in directory: /Users/sergejkrivonos/Library/Caches/pip/wheels/d9/b9/23/e7aa8b7d643b49a3df6532fddf18d7ba3863d706c836d59515
Successfully built enum
Installing collected packages: enum, numpy
Successfully installed enum-0.4.6 numpy-1.12.0
MacBook-Sergej:~ sergejkrivonos$ conda create --name universe-starter-agent python=3.5
Traceback (most recent call last):
  File "/usr/local/bin/conda", line 7, in <module>
    from conda.cli.main import main
  File "/usr/local/lib/python2.7/site-packages/conda/cli/__init__.py", line 8, in <module>
    from .main import main  # NOQA
  File "/usr/local/lib/python2.7/site-packages/conda/cli/main.py", line 46, in <module>
    from ..base.context import context
  File "/usr/local/lib/python2.7/site-packages/conda/base/context.py", line 18, in <module>
    from ..common.configuration import (Configuration, MapParameter, PrimitiveParameter,
  File "/usr/local/lib/python2.7/site-packages/conda/common/configuration.py", line 40, in <module>
    from ruamel.yaml.comments import CommentedSeq, CommentedMap  # pragma: no cover
ImportError: No module named ruamel.yaml.comments
MacBook-Sergej:~ sergejkrivonos$ pip install ruamel.yaml.comments
Collecting ruamel.yaml.comments
  Could not find a version that satisfies the requirement ruamel.yaml.comments (from versions: )
No matching distribution found for ruamel.yaml.comments

**Comment by iHateInventNames** [comment]
this may be overcomed by adding ruamel_yaml dependency http://stackoverflow.com/questions/41373834/conda-importerror-no-module-named-ruamel-yaml-comments

next problem
$ conda create --name universe-starter-agent python=3.5
An unexpected error has occurred.
Please consider posting the following information to the
conda GitHub issue tracker at:

    https://github.com/conda/conda/issues



Traceback (most recent call last):
  File "/usr/local/bin/conda", line 9, in <module>
    load_entry_point('conda==4.2.7', 'console_scripts', 'conda')()
  File "/usr/local/lib/python2.7/dist-packages/conda/cli/main.py", line 150, in main
    return conda_exception_handler(_main)
  File "/usr/local/lib/python2.7/dist-packages/conda/exceptions.py", line 488, in conda_exception_handler
    print_unexpected_error_message(e)
  File "/usr/local/lib/python2.7/dist-packages/conda/exceptions.py", line 436, in print_unexpected_error_message
    info_stdout, info_stderr = get_info()
  File "/usr/local/lib/python2.7/dist-packages/conda/exceptions.py", line 395, in get_info
    from conda.cli import conda_argparse
  File "/usr/local/lib/python2.7/dist-packages/conda/cli/conda_argparse.py", line 15, in <module>
    from .common import add_parser_help
  File "/usr/local/lib/python2.7/dist-packages/conda/cli/common.py", line 16, in <module>
    from ..resolve import MatchSpec
  File "/usr/local/lib/python2.7/dist-packages/conda/resolve.py", line 14, in <module>
    from .logic import minimal_unsatisfiable_subset, Clauses
  File "/usr/local/lib/python2.7/dist-packages/conda/logic.py", line 31, in <module>
    import pycosat
ImportError: No module named pycosat


I guess you need to try pip install on pristine system to track all dependencies.

**Comment by tlbtlbtlb** [comment]
Your conda installation is damaged. Start with a fresh conda env, following the documentation here: https://conda.io/docs/using/envs.html

**Comment by iHateInventNames** [comment]
alright, do not bother with such a little thing as unability to set your project up
